In [1]:
import numpy as np

In [2]:
M = np.matrix('1 0 3; 3 7 2; 2 -2 8; 0 -1 1; 5 8 7')

In [3]:
print(M)

[[ 1  0  3]
 [ 3  7  2]
 [ 2 -2  8]
 [ 0 -1  1]
 [ 5  8  7]]


In [4]:
M.T

matrix([[ 1,  3,  2,  0,  5],
        [ 0,  7, -2, -1,  8],
        [ 3,  2,  8,  1,  7]])

In [5]:
np.dot(M,M.T)

matrix([[ 10,   9,  26,   3,  26],
        [  9,  62,   8,  -5,  85],
        [ 26,   8,  72,  10,  50],
        [  3,  -5,  10,   2,  -1],
        [ 26,  85,  50,  -1, 138]])

In [6]:
np.dot(M.T,M)

matrix([[ 39,  57,  60],
        [ 57, 118,  53],
        [ 60,  53, 127]])